server:
  port: 8080 # Puerto estándar para la capa de acceso (BFF)

spring:
  application:
    name: donaton-bff # Identificador con el que se registrará en Eureka

# Configuración del Cliente Eureka (Descubrimiento)
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL del servidor de infraestructura Eureka
  instance:
    prefer-ip-address: true

# Configuración de Logs (Centralización básica por consola y archivo)
logging:
  level:
    root: INFO
    cl.duoc.donaton: DEBUG # Muestra logs detallados de tus clases en la consola
  file:
    name: logs/donaton-bff.log # Guarda los logs en un archivo para auditoría externa
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuración de Resilience4j para el Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      msDonacionesCB: # Nombre del circuito para las llamadas a MS-Donaciones
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5 # Analiza las últimas 5 llamadas
        failureRateThreshold: 50 # Abre el circuito si el 50% falla
        waitDurationInOpenState: 10000 # Espera 10 segundos en estado abierto antes de probar si revivió
        permittedNumberOfCallsInHalfOpenState: 3
      msLogisticaCB: # Nombre del circuito para las llamadas a MS-Logística
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
      msNecesidadesCB: # Nombre del circuito para las llamadas a MS-Necesidades
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000