server:
  port: 8080

spring:
  application:
    name: donaton-bff

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# 🛡️ Configuración base para monitorear los Circuit Breakers en Consola
resilience4j:
  circuitbreaker:
    instances:
      donacionesCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000ms # Se mantiene abierto por 10 segundos antes de reintentar
        permittedNumberOfCallsInHalfOpenState: 3
      logisticaCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3
      necesidadesCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000ms
        permittedNumberOfCallsInHalfOpenState: 3

# Habilitar métricas de salud para que aparezcan en el Panel de Administración (Admin Panel)
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, resilience4j
  endpoint:
    health:
      show-details: always