version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: donaton-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 300s

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-campanas:
    build: ./ms-campanas
    container_name: ms-campanas
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_campanas?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  ms-voluntarios:
    build: ./ms-voluntarios
    container_name: ms-voluntarios
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_voluntarios?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  ms-donaciones:
    build: ./ms-donaciones
    container_name: ms-donaciones
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_donaciones?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  donaton-bff:
    build: ./donaton-bff
    container_name: donaton-bff
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy

  admin-panel:
    build: ./admin-panel
    container_name: admin-panel
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy

  donaton-front:
    build: ./donaton-front
    container_name: donaton-front
    ports:
      - "3000:80"
    depends_on:
      - donaton-bff
