server:
  port: 8083

spring:
  application:
    name: ms-necesidades
  datasource:
    url: jdbc:mysql://localhost:3306/db_donaciones?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root # Tu usuario de MySQL local
    password: root # Tu contraseña de MySQL local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true